name = "PhysicalSystemsOfUnits"
uuid = "84ba71cf-1dc3-4ac8-8ef7-c99b2cd0dd1c"
authors = ["Alan Freed <alan.d.freed@proton.me>"]
version = "0.1.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"